[server]
host = "127.0.0.1"
port = 8443

[tls]
certfile = "src/gebrauchtwagen/config/resources/tls/certificate.pem"
keyfile = "src/gebrauchtwagen/config/resources/tls/key.pem"

[db]
host = "127.0.0.1"
port = 5432
name = "gebrauchtwagen"
username = "gebrauchtwagen"
password = "gebrauchtwagen"
echo = false

[keycloak]
schema = "https"
host = "localhost"
port = 8843
realm = "python"
client_id = "python-client"
client_secret = "kysQimBCxPWwsicPAX1qktmaYk6Thk8G"
verify = false
